tdclient/api.py, tdclient/client.py, tdclient/import_api.py, tdclient/model.py, tdclient/test/api_test.py, tdclient/test/client_test.py, tdclient/test/export_api_test.py, tdclient/test/import_api_test.py
The original `import_data` requires the data to be formatted in `msgpack.gz`. I added a wrapper method named `import_file` around `import_data`. It will parse a given file and convert it into `msgpack.gz`, then upload to Treasure Data.
Because the `import_file` will decompress and unpack once and then convert into `msgpack.gz`, it's not for the best performance. Although, it would make importing data into Treasure Data easy from Python scripts.
=> Add `import_file` wrapper function

.gitignore
Ignore JetBrains `.idea` directory
JetBrains IDE such as PyCharm are popular for Python development. I also use vim and PyCharm for Python development. I would like to ignore `.idea` directory.
Reference for gitignore for JetBrains IDE.
https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore
AFAIK, .idea is sufficient to ignore PyCharm.
=> update gitignore for JetBrains IDE

README.md
Remove unused module in the example in README
According to README,
`os` and `sys` are not used.
```
#!/usr/bin/env python
import os   # NOT USED
import sys   # NOT USED
import tdclient
with tdclient.Client() as td:
for job in td.jobs():
print(job.job_id)
```
NOTE:
TD site has the similar mistake.
http://docs.treasuredata.com/articles/rest-api-python-client
In Issue Queries
```
import os
import tdclient
import time
apikey = os.getenv("TD_API_KEY")
with tdclient.Client(apikey) as client:
job = client.query("sample_datasets", "SELECT COUNT(1) FROM www_access")
job.wait()
for row in job.result():
print(row)
```
`time` is not needed.
=> remove unused module in the example in README

tdclient/api.py, tdclient/test/import_api_test.py, tdclient/test/test_helper.py
msgpack's integer cannot exceed 64bit. During importing data, current implementation will raise `OverflowError` on packing data into `msgpack.gz` if there is `long` value.
As a workaround, as same as [td toolbelt](https://github.com/treasure-data/td) is doing, pack those values in string.
```
>>> import msgpack
>>> msgpack.packb(1<<64)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/yyuu/.pyenv/versions/3.4.3/lib/python3.4/site-packages/msgpack/__init__.py", line 47, in packb
return Packer(**kwargs).pack(o)
File "msgpack/_packer.pyx", line 223, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:223)
File "msgpack/_packer.pyx", line 225, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:225)
File "msgpack/_packer.pyx", line 140, in …
```
=> BigInt as string

tdclient/schedule_api.py, tdclient/test/schedule_api_test.py
I got an exception when I created a schedule with 'cron' = ''.  This is a valid schedule meaning that the query is not scheduled to run.
```python
In [1]: import tdclient
In [2]: c = tdclient.Client()
In [3]: c.create_schedule('test1', {'database': 'db1', 'cron': '', 'query': 'select 1'})
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-28-82b4b391c57e> in <module>()
----> 1 c.create_schedule('test1', {'database': 'db1', 'cron': '', 'query': 'select 1'})
/Users/knishida/miniconda/envs/pandas3/lib/python3.4/site-packages/tdclient/client.py in create_schedule(self, name, params)
511             raise ValueError("'query' option is required")
512         params = {} if params …
```
=> avoid an exception raised when "start" is nil

tdclient/client.py, tdclient/job_model.py, tdclient/test/job_model_test.py
Database name of a job is accessible by 'database', not 'db_name':
https://github.com/treasure-data/td-client-python/blob/master/tdclient/job_api.py#L84
I confirmed this patch fixes the issue:
```python
In [1]: import tdclient
In [2]: c = tdclient.Client()
In [3]: j = c.job(42334874)
In [4]: j.database
Out[4]: 'production'
```
This patch breaks backward compatibility, but I think it's acceptable because the old code have never worked.
=> fix getting database names of job objects

tdclient/api.py, tdclient/connector_api.py, tdclient/test/api_test.py, tdclient/test/connector_api_test.py
DataConnector's request parameter is nested dictionary of JSON. It should be sent as request body with `Content-Type: application/json`.
=> Handle request parameters of DataConnector jobs properly

tdclient/api.py, tdclient/test/api_test.py
Do putting multiple times might produce same data multiple. This just let td-client-python to prevent retry after any `PUT` failures.
This is the same behaviour as https://github.com/treasure-data/td-client-ruby
=> Prevent retry after PUT request failures

tdclient/account_api.py, tdclient/account_model.py, tdclient/client.py, tdclient/database_api.py, tdclient/database_model.py, tdclient/table_model.py, tdclient/test/client_test.py, tdclient/test/database_api_test.py, tdclient/user_model.py
Using keyword arguments could be better than listing bunch of variables as parameters of `__init__`.
=> Use keyword arguments for initializing model attributes

requirements.txt, tdclient/api.py, tdclient/test/api_test.py
On Python 2.x, if we pass some unicode objects to urllib3, underlying `httplib` will raise `UnicodeDecodeError` like following.
```
Traceback (most recent call last):
File "./x.py", line 13, in <module>
cursor.execute(query)
File "/home/yyuu/work/repos/git/treasure-data/td-client-python/tdclient/cursor.py", line 45, in execute
self._executed = self._api.query(query, **self._query_kwargs)
File "/home/yyuu/work/repos/git/treasure-data/td-client-python/tdclient/job_api.py", line 229, in query
with self.post("/v3/job/issue/%s/%s" % (urlquote(str(type)), urlquote(str(db))), params) as res:
File "/home/yyuu/work/repos/git/treasure-data/td-client-python/tdclient/api.py", line 220, in post
response = self.send_request("POST", url, fields=fields, body=body, headers=headers, decode_content=True, …
```
=> Pass string arguments to as in byte representation on Python 2.x

CHANGELOG.md, tdclient/api.py
Without this, `UnicodeDecodeError` will occur if we specify request parameters as `str` instead of `unicode`. This should allow users to specify either `str` or `unicode`.
```
In [1]: job = td.query(u'sample_datasets', "SELECT 'こんにちは'", type='presto')
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-2-023ebc33ffee> in <module>()
----> 1 job = td.query(u'sample_datasets', "SELECT 'こんにちは'", type='presto')
/home/yyuu/work/repos/git/treasure-data/td-client-python/tdclient/client.pyc in query(self, db_name, q, result_url, priority, retry_limit, type, **kwargs)
217         if type not in ["hive", "pig", "impala", "presto"]:
218             raise ValueError("The specified query …
```
=> Allow specify request parameters in `str` instead of `unicode` on Python 2.x

tdclient/api.py
As per https://pypi.python.org/pypi/msgpack-python,
"Currently, while msgpack-python supports new bin type, default
setting doesn't use it and decodes raw as bytes instead of
unicode (str in Python 3).
=> Fix for erroneous missing 'time' column warning

tdclient/api.py, tdclient/job_api.py
This should fix #35 in favor of it. Note that `start_at` and `end_at` will be `None` if the API returned empty string as these values.
=> Ignore empty string in job's `start_at` and `end_at`

tdclient/client.py, tdclient/job_api.py, tdclient/job_model.py, tdclient/test/job_api_test.py, tdclient/test/job_model_test.py
Support the following parameters for list jobs and show job;
- created_at
- updated_at
- num_records
- user_name
- linked_result_export_job_id
- result_export_target_job_id
Could you review this?
=> #39 Support missing parameters in JOB API

.travis.yml, requirements.txt, setup.py, tox.ini
Management of dependencies of overall application is a responsibility of application itself. This change is to let application to manage their dependencies at their own risk.
=> Tweaking library dependency versions & deprecate 2.6 completely

tdclient/cursor.py, tdclient/test/cursor_test.py
Continued from #43.
So far [DBAPI2](https://www.python.org/dev/peps/pep-0249/) interface of td-client-python was implemented to raise some exception for empty result set of a query because I interpreted that "previous call to `.execute*()` did not produce any result set or no call was issued yet" was requesting so.
> fetchone()
> ( ... )
> An Error (or subclass) exception is raised if the previous call to .execute*() did not produce any result set or no call was issued yet.
https://www.python.org/dev/peps/pep-0249/#fetchone
However, it looks like somehow I overlooked the first sentence of the description; it should return `None` when no more data is available.
> Fetch the next row of a query result set, returning a single sequence, or None when no more data is available. [6] …
=> Return `None` or `[]` on `fetchone` and `fetchall` with empty result set of query instead of raising exception (fixes #43)

README.md
README doesn't tell us what types of endpoints are available besides the default one.
=> Add link to a list of sites and endpoints

requirements.txt
Since urllib3 v1.22 has a vulnerability, this PR will fix the issue.
https://github.com/treasure-data/td-client-python/network/alert/requirements.txt/urllib3/open
=> Set urllib3 minimum version as v1.24.1

tdclient/api.py, tdclient/table_api.py
While `API` class assumes `tail` function, there is no implementation for `TableAPI` class. This PR introduces the `TableAPI.tail` method, to enable the capability.
Before:
```py
In [36]: with tdclient.Client() as td:
...:     td.tail("aki", "iris", 10)
...:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-36-e94fce9ef607> in <module>
1 with tdclient.Client() as td:
----> 2     td.tail("aki", "iris", 10)
3
~/src/td-client-python/tdclient/client.py in tail(self, db_name, table_name, count, to, _from, block)
190         TODO: add docstring
191         """
--> 192         return self.api.tail(db_name, table_name, count, to, _from, block)
193
194     def query(
AttributeError: …
```
=> Implement TableAPI.tail method

tdclient/api.py, tdclient/bulk_import_api.py, tdclient/client.py, tdclient/database_model.py, tdclient/job_api.py, tdclient/table_api.py, tdclient/test/api_test.py, tdclient/test/client_test.py, tdclient/test/connection_test.py, tdclient/test/cursor_test.py, tdclient/test/database_api_test.py, tdclient/test/export_api_test.py, tdclient/test/job_api_test.py, tdclient/test/partial_delete_api_test.py, tdclient/test/pseudo_certifi_test.py, tdclient/test/result_api_test.py, tdclient/test/result_model_test.py, tdclient/test/schedule_api_test.py, tdclient/test/schedule_model_test.py, tdclient/test/server_status_api_test.py, tdclient/test/table_api_test.py, tdclient/test/table_model_test.py, tdclient/test/test_helper.py, tdclient/test/user_api_test.py, tdclient/test/user_model_test.py, tdclient/user_api.py
This PR removes:
1. `change_email`, `change_password `, `change_my_password ` methods those are not public API anymore
2. Unused authentication-related methods
3. Py2 dependent codes
4. item table related codes
5. `encoding` option for `msgpack.Unpacker`. Use `raw=False` instead
6. Deprecated options and methods like:
- remove connect_timeout, read_timeout, send_timeout options for API
- remove API.sleep, API.parsedate methods
- remove JobAPI.hive_query, JobAPI.presto_query methods
=> Cleanup non-public API call, Py2 dependent codes, and Deprecated codes

tdclient/bulk_import_model.py, tdclient/job_model.py
While `BulkImport.perform()` has `wait_callback` argument, but never used.
Also, remove `callback` argument in `Job.wait()`
=> Handle wait_interval argument of BulkImport.perform() appropriately

tdclient/api.py, tdclient/test/test_helper.py
Fixes #76 
```py
n [1]: import pandas as pd
In [2]: import tdclient
In [3]: td = tdclient.Client()
In [4]: df = pd.DataFrame(data={'col1': [1, 2], 'col2': [3, 10], 'col3': ['foo', "\x85."]})
In [5]: fname = "/tmp/foo.csv"
In [6]: df.to_csv(fname)
In [7]: import time
In [8]: session_name = f"session-{int(time.time())}"
In [10]: td.create_log_table("aki", "test")
Out[10]: True
In [23]: df['time'] = int(time.time())
In [24]: df.to_csv(fname)
In [25]: session_name = f"session-{int(time.time())}"
In [26]: bulk_import = td.create_bulk_import(session_name, "aki", "test")
In [27]: bulk_import.freeze()
Out[27]: True
In [29]: bulk_import.delete()
Out[29]: True
In [30]: session_name = f"session-{int(time.time())}"
In [31]: bulk_import = td.create_bulk_import(session_name, "aki", "test")
In [32]: …
```
=> Use io.TextIOWrapper to prevent "x85" issue creating None

CHANGELOG.rst, README.rst, docs/api/misc.rst, docs/file_import_parameters.rst, docs/index.rst, tdclient/api.py, tdclient/bulk_import_api.py, tdclient/bulk_import_model.py, tdclient/client.py, tdclient/import_api.py, tdclient/test/dtypes_and_converters_test.py, tdclient/test/test_helper.py, tdclient/util.py
Add new (optional) parameters to `ImportApi.import_files`, `BulkImportApi.bulk_import_upload_file` and `BulkImport.upload_file`.
The `dtypes` and `converters` parameters allow better control of the import of CSV data. This is modelled on the approach taken by pandas.
Existing tests pass, and new tests also pass. Coverage has gone up, and the new code is covered.
Extra documentation has been added to cover the possibilities for `**kwargs` arguments when processing CSV data, and some extra description of what `file-like` means (I hope this is useful for those, like me, who are new to the library).
While I was writing docstrings for the new functions in utils.py, I also updated some of the other docstrings in that same file.
=> Issue 83: Support explicit column datatypes in CSV

requirements.txt, tdclient/connector_api.py, tdclient/test/connector_api_test.py, tdclient/test/util_test.py, tdclient/util.py
`ConnectorAPI.connector_guess` requires a certain format, at least it should have `config` key in a JSON. This change ensures to have `config` key in the `job` argument for `ConnectorAPI.connector_guess`.
Also, removing unexistent api in the doc.
=> Ensure config key for ConnectorAPI.connector_guess

setup.py
td-client-python doesn't work with msgpack-v1.0.0.
This fix forces to install msgpack v0.6.2 since it is the latest version and it's same as requirements.tx
```
$ pip install td-client
Collecting td-client
Using cached td_client-1.2.0-py3-none-any.whl (86 kB)
Collecting msgpack>=0.5.2
Downloading msgpack-1.0.0-cp37-cp37m-macosx_10_13_x86_64.whl (78 kB)
|████████████████████████████████| 78 kB 3.6 MB/s 
Requirement already satisfied: python-dateutil in ./.pyenv/versions/3.7.4/lib/python3.7/site-packages (from td-client) (2.8.0)
Requirement already satisfied: urllib3 in ./.pyenv/versions/3.7.4/lib/python3.7/site-packages (from td-client) (1.24.3)
Requirement already satisfied: six>=1.5 in ./.pyenv/versions/3.7.4/lib/python3.7/site-packages (from python-dateutil->td-client) (1.12.0) …
```
=> Use msgpack v0 instead of v1

tdclient/api.py, tdclient/test/api_test.py
If a user doesn't give a scheme for an endpoint, `http` will be used, e.g., `api.ap02.treasuredata.com` treated as `http://api.ap02.treasuredata.com`. This doesn't work new endpoints, i.e., ap02, since ap02 allows `https` only.
This patch ensures to use `https` if the scheme not given with endpoint.
=> Ensure endpoint starts with 'https://' if scheme not given

README.rst, tdclient/schedule_api.py
I replaced Treasure Data older document URL since theses can't redirect correctly.
=> Update documentation URLs

README.rst
I have fixed the following two links:
1. Treasure Data Documentation seems to be https://dos.treasuredata.com now, so I changed the url to the corresponding url in the new domain.
2. I fixed the path for file_import_parameters.html
=> Fixed some broken links to documentation.

CHANGELOG.rst, README.rst, tdclient/bulk_import_api.py, tdclient/bulk_import_model.py, tdclient/client.py, tdclient/connector_api.py, tdclient/schedule_api.py
This pull request fixes a few typo/misspellings. While reading the source code, I found these errors (PyCharm's editor helped me a lot).
=> Fix typo/misspelled words in docstrings etc.

setup.py
the `long_description_content_type`  wasn't compliant with PEP 566, check [here](https://packaging.python.org/en/latest/specifications/core-metadata/#description-content-type) for the documentation. This seems to cause a failure when trying to download the library from a private azure devops feed setted up with pypi as upstream source. During the download raises a `HTTP error 400 Client Error: Bad Request - The package description content type is invalid. It should conform to the format described in PEP 566.` Compliance with PEP 566 has been broken since version 1.0.0, downloading in the same way the version 0.14.0 works correctly.
=> fix long_description_content_type for PEP 566 compliance

tdclient/job_api.py, tdclient/test/test_helper.py
When the job result is large, 100MiB or more, td-client-python gets `urllib3.exceptions.ReadTimeoutError`.
To prevent it, change to explicitly read response with limited size of response, and feed the response to `Unpacker.feed()`.
```py
>>> import tdclient; import os; td = tdclient.Client(apikey=os.environ["TD_API_KEY"])
>>> job = tdclient.job_model.Job(td, "2172129677", "presto", "select 1")
>>> len(list(job.result_format("msgpack")))
Traceback (most recent call last):
File "/Users/ariga/src/td-client-python/.venv/lib/python3.12/site-packages/urllib3/response.py", line 748, in _error_catcher
yield
File "/Users/ariga/src/td-client-python/.venv/lib/python3.12/site-packages/urllib3/response.py", line 873, in _raw_read
data = self._fp_read(amt, read1=read1) if not fp_closed else b"" …
```
=> Use `msgpack.Unpacker.feed()` method to prevent ReadTimeoutError

tdclient/api.py, tdclient/client.py, tdclient/job_api.py, tdclient/test/job_api_test.py, tdclient/test/test_helper.py
This method downloads the result of a job to a
local file in msgpack.gz format. It can specify
thread number for parallel download.
Confirmed that checksum is the same as a downloaded file by TD toolbelt.
```sh
$ shasum 2172017217*
5e227ef6582fd216ce1f0d8b81d43a4a6274aff6  2172017217.msgpack.gz
5e227ef6582fd216ce1f0d8b81d43a4a6274aff6  2172017217_toolbelt.msgpack.gz
```
- TD Toolbelt: 37 mins (including one retry)
- td-client-python with 6 threads: 4 mins
```sh
$ time /Users/ariga/.gem/ruby/2.6.0/bin/td job:show 2172017217 -f msgpack.gz -o 2172017217_toolbelt.msgpack.gz
JobID       : 2172017217
Status      : success
Type        : presto
Database    : aki_audience_large
Start At    : 2024-08-17 08:52:04 UTC
End At      : 2024-08-17 09:03:29 UTC
Priority    : NORMAL
Retry limit : 0
Output …
```
=> Add download_job_result method to JobAPI

tdclient/api.py, tdclient/client.py, tdclient/job_api.py, tdclient/job_model.py, tdclient/test/client_test.py, tdclient/test/job_api_test.py, tdclient/test/job_model_test.py, tdclient/test/test_helper.py
This PR depends on  #118 and #119. Please merge after them.
The main contribution is [69bb7e9](https://github.com/treasure-data/td-client-python/pull/120/commits/69bb7e924bfbd06e8d9f8b1498107169a44d162d)
This patch allows the download of large query results in parallel.
The following evaluation shows iteration over 1GiB query result speeds up 8 times.
```py
>>> import time; s = time.time(); len(list(td.api.job_result_format_each("2172739824", "msgpack", store_tmpfile=True, num_threads=6))); print(f"elapsed time: {time.time() - s} sec")
33000000
elapsed time: 208.30903315544128 sec
```
```py
>>> import tdclient; import os; td = tdclient.Client(apikey=os.environ["TD_API_KEY"])
>>> import time; s = time.time(); len(list(td.api.job_result_format_each("2172739824", "msgpack", …
```
=> Add store_tmpfile option to job_result_format_each() method to JobAPI and Client

tdclient/client.py, tdclient/database_model.py, tdclient/result_api.py, tdclient/result_model.py, tdclient/schedule_model.py, tdclient/table_api.py, tdclient/table_model.py, tdclient/test/database_api_test.py, tdclient/test/database_model_test.py, tdclient/test/result_api_test.py, tdclient/test/result_model_test.py, tdclient/test/schedule_api_test.py, tdclient/test/schedule_model_test.py, tdclient/test/table_api_test.py, tdclient/test/table_model_test.py
This reverts commit e8d1b957892f12e056a95ff5d957c5dc450b3acd
=> Revert "Update response for database, table, result and schedule list APIs (#117)"

.github/workflows/python-publish.yml
Due to adoption of pyproject.toml instead of setup.py: https://github.com/treasure-data/td-client-python/pull/122, we need to update python-publish script
=> Update build step of python-publish script

README.rst, pyproject.toml
- Support Python from 3.8 to 3.12.
- [Internal] Use `Unpacker.feed` to download msgpack data.
- New `download_job_result` API to download the job result to local msgpack file.
- Support download job result to local file with new `store_tmpfile` (bool, optional) and `num_threads` (int, optional) parameters in `job_result_format_each` API.
- Support fetching header info with new headers parameter in `job_result_format_each` and `job_result_format_each` APIs.
- Various docstring updates.
=> Release 1.3.0

tdclient/job_api.py, tdclient/test/job_api_test.py
Fixes an obscure bug(?) where certain tables being downloaded as zipped `msgpack` files would not be read correctly by `gzip` during unpacking, if temporary file storage is used. The files would seemingly become corrupt, causing the following stacktrace:
```
File ~/.pyenv/versions/3.11.10/lib/python3.11/site-packages/tdclient/client.py:353, in Client.job_result_format_each(self, job_id, format, header, store_tmpfile, num_threads)
336 def job_result_format_each(
337     self, job_id, format, header=False, store_tmpfile=False, num_threads=4
338 ):
339     """
340     Args:
341         job_id (str): job id
(...)
351          an iterator of rows in result set
352     """
--> 353     for row in self.api.job_result_format_each(
354         job_id,
355         format,
356         header=header, …
```
=> [JobAPI] Multithreaded Temporary File Storage: Replace `gzip` with `open()`

tdclient/job_api.py, tdclient/test/job_api_test.py
Reverts treasure-data/td-client-python#127
While investigating the root cause of the issue in #127, I found that the cause was the server side issue, not client side.
`job.result_size` returned by td-api of the development environment was corrupted. Hence, there was a miscalculation of the chunk size.
https://github.com/treasure-data/td-client-python/blob/cbb40045ede01bbd69720502cb5ee4e2dc502787/tdclient/job_api.py#L349-L350
Also, using the msgpack.gz request is critical because `job.result_size` assumes msgpack.gz size.
https://github.com/treasure-data/td-client-python/blob/cbb40045ede01bbd69720502cb5ee4e2dc502787/tdclient/job_api.py#L307
Therefore, revert #127
=> Revert "[JobAPI] Multithreaded Temporary File Storage: Replace `gzip` with `open()`"

.gitignore, tdclient/client.py, tdclient/job_api.py, tdclient/test/client_test.py
=> Support trino type query
